# Generated by Django 5.0 on 2023-12-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.FileField(upload_to='eventapp/static')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('district', models.CharField(choices=[('Kasargod', 'Kasargod'), ('Kannur', 'Kannur'), ('Kozhikode', 'Kozhikode'), ('Wayanad', 'Wayanad'), ('Malappuram', 'Malappuram'), ('Thrissur', 'Thrissur'), ('Palakkad', 'Palakkad'), ('Thrissur', 'Thrissur'), ('Eranakulam', 'Eranakulam'), ('Kottayam', 'Kottayam'), ('Alappuzha', 'Alappuzha'), ('Pathanamthitta', 'Pathanamthitta'), ('Kollam', 'Kollam'), ('Thiruvananthapuram', 'Thiruvananthapuram')], max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
