# Generated by Django 5.0 on 2023-12-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='usertype',
            field=models.CharField(choices=[('company', 'company'), ('customer', 'customer')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='website',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
