# Generated by Django 5.0 on 2023-12-11 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0002_register_usertype_register_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventbookmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('event_type', models.CharField(choices=[('Wedding', 'Wedding'), ('Reception', 'Reception'), ('Engagement', 'Engagement'), ('House warming', 'House warming'), ('Bachelor party', 'Bachelor party'), ('Birthday part', 'Birthday part'), ('Others', 'Others')], max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('phone', models.IntegerField()),
                ('alternate_phone', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventapp.register')),
            ],
        ),
    ]
