# Generated by Django 5.0 on 2023-12-11 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_eventbookmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventbookmodel',
            old_name='user',
            new_name='team',
        ),
    ]
