# Generated by Django 5.0 on 2023-12-11 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_rename_user_eventbookmodel_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbookmodel',
            name='team',
        ),
        migrations.AddField(
            model_name='eventbookmodel',
            name='usertype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eventapp.register'),
        ),
    ]
