# Generated by Django 5.0 on 2023-12-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0005_remove_eventbookmodel_team_eventbookmodel_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbookmodel',
            name='usertype',
        ),
        migrations.AddField(
            model_name='eventbookmodel',
            name='event_team',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
