# Generated by Django 5.0 on 2023-12-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0006_remove_eventbookmodel_usertype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='confirm_booking_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('date_of_booking', models.DateField()),
                ('event_date', models.DateField()),
                ('phone', models.IntegerField()),
                ('altern_phone', models.IntegerField()),
                ('exp_amount', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('confirm_order', models.CharField(choices=[('accept', 'accept'), ('reject', 'reject')], max_length=50)),
            ],
        ),
    ]
