# Generated by Django 5.0 on 2023-12-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0007_confirm_booking_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirm_booking_model',
            name='event_team',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
