# Generated by Django 5.0 on 2023-12-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0008_confirm_booking_model_event_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviewmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=100)),
                ('event_teams', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=400)),
            ],
        ),
    ]
