# Generated by Django 5.0 on 2023-12-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0009_reviewmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='rating',
            field=models.CharField(choices=[('5star', '5star'), ('4star', '4star'), ('3star', '3star'), ('2star', '2star'), ('1star', '1star')], max_length=50),
        ),
    ]
