# Generated by Django 5.0 on 2024-01-10 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0011_admin_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbookmodel',
            name='booked_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
