# Generated by Django 5.0 on 2024-01-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0012_eventbookmodel_booked_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbookmodel',
            name='booked_date',
        ),
    ]
